const data = {
    sliderItems: [
        {
            _id:1,
            image: "/images/slider/bg1.jpg"
        },
        {
            _id:2,
            image: "/images/slider/bg2.jpg"
        },
        {
            _id:3,
            image: "/images/slider/bg3.jpg"
        }
    ],

    category: [
        {
            _id: 1,
            title: "Samsung",
            image:"/images/merk/samsung.png"
        },
        {
            _id: 2,
            title: "Apple",
            image:"/images/merk/iphone.png"
        },
        {
            _id: 3,
            title: "Vivo",
            image:"/images/merk/vivo.png"
        },
        {
            _id: 4,
            title: "Oppo",
            image:"/images/merk/oppo.png"
        }
    ],

    products: [
        {
            _id: 1,
            title: "Samsung Galaxy M53 5G",
            slug: 'product1',
            OS: "OS: Android 12, One UI 4.1",
            CPU: "CPU: Octa-core (2x2.4 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)",
            RAM: "RAM: 8 GB",
            Memori: "Memori: 128 GB",
            Dimensi: "Dimensi: 164.7 x 77 x 7.4 mm (6.48 x 3.03 x 0.29 in), 176 g",
            Layar: "Layar: 6.7 inches, 1080 x 2408 pixels, 20:9 ratio",
            Kamera_utama: "Kamera utama: 108 MP (wide), 8 MP (ultrawide), 2 MP (macro), 2 MP (depth)",
            Kamera_depan: "Kamera depan: 32 MP, f/2.2, 26mm (wide)",
            Baterai: "Baterai: Li-Ion 5000 mAh",
            Warna: "Warna: Green, Blue, Brown",
            category: "Samsung",
            image: "/images/products/Samsung Galaxy M52 5G/Samsung_Galaxy_M53_5G_1.jpg",
            image1: "/images/products/Samsung_Galaxy_M53_5G_2.png",
            image2: "/images/products/Samsung_Galaxy_M53_5G_2.png",
            image3: "/images/products/Samsung_Galaxy_M53_5G_1.png",
            image4: "/images/products/Samsung_Galaxy_M53_5G_2.png",
            countInStock: 1,
            price: "6399000",
        },
        {
            _id: 2,
            title: "Samsung Galaxy M52 5G",
            slug: 'product2',
            OS: "OS: Android 12, One UI 4.1",
            CPU: "CPU: Octa-core (4x2.4 GHz Kryo 670 & 4x1.8 GHz Kryo 670)",
            RAM: "RAM: 8 GB",
            Memori: "Memori: 128 GB",
            Dimensi: "Dimensi: 164.2 x 76.4 x 7.4 mm (6.46 x 3.01 x 0.29 in), 173 g",
            Layar: "Layar: 6.7 inches, 1080 x 2400 pixels, 20:9 ratio",
            Kamera_utama: "Kamera utama: 64 MP (wide), 12 MP (ultrawide), 5 MP (macro)",
            Kamera_depan: "Kamera depan: 32 MP, f/2.2, (wide)",
            Baterai: "Baterai: Li-Ion 5000 mAh",
            Warna: "Warna: Icy Blue, Blazing Black, White",      
            category: "Samsung",
            image: "/images/products/Iphone_SE_1.jpg",
            image1: "/images/products/Iphone_SE_2.jpg",
            image2: "/images/products/Iphone_SE_1.jpg",
            image3: "/images/products/Iphone_SE_2.jpg",
            image4: "/images/products/Iphone_SE_1.jpg",
            countInStock: 5,
            price: "5490000",
        },
        {
            _id: 3,
            title: "Apple iPhone SE",
            slug: 'product3',
            OS: "OS: iOS 15.4",
            CPU: "CPU: Hexa-core (2xX.XX GHz Avalanche + 4xX.XX GHz Blizzard)",
            RAM: "RAM: 4 GB",
            Memori: "Memori: 128 GB",
            Dimensi: "Dimensi: 138.4 x 67.3 x 7.3 mm (5.45 x 2.65 x 0.29 in), 144 g",
            Layar: "Layar: 4.7 inches, 750 x 1334 pixels, 16:9 ratio",
            Kamera_utama: "Kamera utama: 12 MP (wide)",
            Kamera_depan: "Kamera depan: 7 MP, f/2.2",
            Baterai: "Baterai: Li-Ion 2018 mAh",
            Warna: "Warna: Black, White, Red",        
            category: "Iphone",
            image: "/images/products/Iphone_SE_1.jpg",
            image1: "/images/products/Iphone_SE_2.jpg",
            image2: "/images/products/Iphone_SE_1.jpg",
            image3: "/images/products/Iphone_SE_2.jpg",
            image4: "/images/products/Iphone_SE_1.jpg",
            countInStock: 5,
            price: "7399000",
        },
        {
            _id: 4,
            title: "Apple iPhone XR",
            slug: 'product4',
            OS: "OS: iOS 12, upgradable to iOS 15.4.1",
            CPU: "CPU: Hexa-core (2x2.5 GHz Vortex + 4x1.6 GHz Tempest)",
            RAM: "RAM: 3 GB",
            Memori: "Memori: 64 GB",
            Dimensi: "Dimensi: 150.9 x 75.7 x 8.3 mm (5.94 x 2.98 x 0.33 in), 194 g",
            Layar: "Layar: 6.1 inches, 828 x 1792 pixels, 19.5:9 ratio",
            Kamera_utama: "Kamera utama: 12 MP (wide)",
            Kamera_depan: "Kamera depan: 7 MP, f/2.2",
            Baterai: "Baterai: Li-Ion 2942 mAh",
            Warna: "Warna: Black, Red, Yellow, Blue, Coral, White",
            category: "Iphone",
            image: "/images/products/Iphone_SE_1.jpg",
            image1: "/images/products/Iphone_SE_2.jpg",
            image2: "/images/products/Iphone_SE_1.jpg",
            image3: "/images/products/Iphone_SE_2.jpg",
            image4: "/images/products/Iphone_SE_1.jpg",
            countInStock: 5,
            price: "7599000",
        },
        {
            _id: 5,
            title: "Oppo Find X3 Pro",
            slug: 'product5',
            OS: "OS: Android 11, upgradable to Android 12, ColorOS 12",
            CPU: "CPU: Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)",
            RAM: "RAM: 12 GB",
            Memori: "Memori: 256 GB",
            Dimensi: "Dimensi: 163.6 x 74 x 8.3 mm (6.44 x 2.91 x 0.33 in), 193 g",
            Layar: "Layar: 6.7 inches, 1440 x 3216 pixels, 20:9 ratio",
            Kamera_utama: "Kamera utama: 50 MP (wide), 13 MP (telephoto), 50 (ultrawide), 3 MP (microscope)",
            Kamera_depan: "Kamera depan: 32 MP, f/2.4",
            Baterai: "Baterai: Li-Po 4500 mAh",
            Warna: "Warna: Gloss Black, Blue, White, Cosmic Mocha, Mars Edition, Photographer Edition",
            category: "Oppo",
            image: "/images/products/Iphone_SE_1.jpg",
            image1: "/images/products/Iphone_SE_2.jpg",
            image2: "/images/products/Iphone_SE_1.jpg",
            image3: "/images/products/Iphone_SE_2.jpg",
            image4: "/images/products/Iphone_SE_1.jpg",
            countInStock: 5,
            price: "16099000",
        },
        {
            _id: 6,
            title: "Oppo A16e",
            slug: 'product6',
            OS: "OS: Android 11, upgradable to Android 12, ColorOS 12",
            CPU: "CPU: Octa-core (1x3.0 GHz Cortex-A78 & 3x2.6 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)",
            RAM: "RAM: 3 GB",
            Memori: "Memori: 32 GB",
            Dimensi: "Dimensi: 160 x 73.1 x 7.6 mm (6.30 x 2.88 x 0.30 in), 177 g",
            Layar: "Layar: 6.55 inches, 1080 x 2400 pixels, 20:9 ratio",
            Kamera_utama: "Kamera utama: 64 MP (wide), 8 MP (ultrawide), 2 MP (macro), 2 MP (depth)",
            Kamera_depan: "Kamera depan: 32 MP, f/2.4",
            Baterai: "Baterai: Li-Po 4500 mAh",
            Warna: "Warna: Black, Blue, Aurora",
            category: "Oppo",
            image: "/images/products/Iphone_SE_1.jpg",
            image1: "/images/products/Iphone_SE_2.jpg",
            image2: "/images/products/Iphone_SE_1.jpg",
            image3: "/images/products/Iphone_SE_2.jpg",
            image4: "/images/products/Iphone_SE_1.jpg",
            countInStock: 5,
            price: "16099000",
        },
        {
            _id: 7,
            title: "Product 7",
            slug: 'product7',
            desc: "Description for Product 4",
            category: "Kids",
            image: "/images/products/21.jpeg",
            image1: "/images/products/22.jpeg",
            image2: "/images/products/23.jpeg",
            image3: "/images/products/24.jpeg",
            countInStock: 15,
            price: "76.00",
        },
        {
            _id: 8,
            title: "Product 8",
            slug: 'product8',
            desc: "Description for Product 4",
            category: "Women",
            image: "/images/products/25.jpeg",
            image1: "/images/products/26.jpeg",
            image2: "/images/products/27.jpeg",
            image3: "/images/products/28.jpeg",
            countInStock: 13,
            price: "45.00",
        }
    ]
}

export default data;